### ISSUE TITLE
提示无法加载 FaceUnity 插件

### ISSUE THREAD

**Issue by raingxm** [AgoraIO-Community/Agora-Electron-FaceUnity-Plugin#7]
控制台报错
App.tsx?85c4:167 failed to load plugin at /Users/xx/Documents/AgoraIO-Community/Agora-Electron-FaceUnity-Plugin/demo/static/fu-mac/libFaceUnityPlugin.dylib

**Comment by plutoless** [comment]
你的libFaceUnityPlugin.dylib是自己编译的吗？还是从release下载的？用的是哪个分支和目录?

**Comment by raingxm** [comment]
我解决了， 应该是配置的 Appid 不对， Appid 设置成那种带 token 的了， 不带 token 的临时版本可以解决这个问题

**Comment by plutoless** [comment]
@raingxm 理论上appid应该只影响你加频道，不应该会影响你加载插件，不过能work就好
